//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRunner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Ergo.ExpertBanker.sln|0</string>
  <string>Ergo.ExpertBanker.Infrastructure.sln|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MaxCoverage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MaxCoverage"]));
            }
            set {
                this["MaxCoverage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\b(test)|(IntegrationTsts)\\b")]
        public string TestPattern {
            get {
                return ((string)(this["TestPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ergo.ExpertBanker.Documents.Tests|Ergo.ExpertBanker.Comments.Tests|Ergo.ExpertBan" +
            "ker.Admin.Tests|Ergo.ExpertBanker.Activity.Tests")]
        public string SkipTestProjects {
            get {
                return ((string)(this["SkipTestProjects"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.office365.com")]
        public string SmtpServer {
            get {
                return ((string)(this["SmtpServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tfsnotifications@fenergo.com")]
        public string SmtpUser {
            get {
                return ((string)(this["SmtpUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tfsnotifications@fenergo.com")]
        public string SmtpFrom {
            get {
                return ((string)(this["SmtpFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmtpSsl {
            get {
                return ((bool)(this["SmtpSsl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fenergo.1234")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Debug")]
        public string MsBuildConfiguration {
            get {
                return ((string)(this["MsBuildConfiguration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fen-tfs.fenergo.com:8080/tfs/product")]
        public string TfsTeamProjectCollection {
            get {
                return ((string)(this["TfsTeamProjectCollection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/InIsolation /EnableCodeCoverage /UseVsixExtensions:true /Logger:trx \"/Logger:Tfs" +
            "Publisher;Collection=http://fen-tfs.fenergo.com:8080/tfs/product;TeamProject={0}" +
            ";BuildName={1};{2}\"")]
        public string VsTestArguments {
            get {
                return ((string)(this["VsTestArguments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7200000")]
        public int ProcessTimeout {
            get {
                return ((int)(this["ProcessTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/x:TestRun/x:ResultSummary[@outcome=\'Failed\']")]
        public string TrxResultSummaryXpath {
            get {
                return ((string)(this["TrxResultSummaryXpath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\IDE\\CommonExtensions\\" +
            "Microsoft\\TestWindow\\vstest.console.exe")]
        public string VsTestPath {
            get {
                return ((string)(this["VsTestPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Team Tools\\Dynamic Code Cover" +
            "age Tools\\CodeCoverage.exe")]
        public string CodeCoveragePath {
            get {
                return ((string)(this["CodeCoveragePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TestRunner\\TestResults")]
        public string TestResultsFolder {
            get {
                return ((string)(this["TestResultsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-*test*;-*IntegrationTsts*")]
        public string CoverageReportFilters {
            get {
                return ((string)(this["CoverageReportFilters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QA28_Nightly_Build")]
        public string BuildDefinition {
            get {
                return ((string)(this["BuildDefinition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SS KYC")]
        public string TeamProject {
            get {
                return ((string)(this["TeamProject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FEN-LAP-053")]
        public string Workspace {
            get {
                return ((string)(this["Workspace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution\\Fenergo.Solution.SSGKYC.sln")]
        public string VsSolutionPath {
            get {
                return ((string)(this["VsSolutionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution\\TestProjects\\Fenergo.Domain.Soluti" +
            "on.SSGKYC.Tests\\bin\\Debug\\Fenergo.Domain.Solution.SSGKYC.Tests.dll")]
        public string UnitTestDll {
            get {
                return ((string)(this["UnitTestDll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution\\TestProjects\\Fenergo.Domain.Soluti" +
            "on.SSGKYC.IntegrationTests\\bin\\Debug\\Fenergo.Domain.Solution.SSGKYC.Integration." +
            "Tests.dll")]
        public string IntegrationTestDll {
            get {
                return ((string)(this["IntegrationTestDll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution\\TestProjects\\Fenergo.Domain.Soluti" +
            "on.SSGKYC.ConfigurationTests\\bin\\Debug\\Fenergo.Domain.Solution.SSGKYC.Configurat" +
            "ion.Tests.dll")]
        public string ConfigurationTestDll {
            get {
                return ((string)(this["ConfigurationTestDll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution\\Fenergo.ServiceImplementation.Solu" +
            "tion.SSGKYC.Tests\\bin\\Debug\\Fenergo.ServiceImplementation.Solution.SSGKYC.Tests." +
            "dll")]
        public string ServiceImplementationTestDll {
            get {
                return ((string)(this["ServiceImplementationTestDll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\dev-merges\\Dev-Merges\\Fenergo.Solution")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\MSBuild.exe")]
        public string Compiler {
            get {
                return ((string)(this["Compiler"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OracleServiceFENERGO2")]
        public string OracleServiceName {
            get {
                return ((string)(this["OracleServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/TestResults/")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ForceExecution {
            get {
                return ((string)(this["ForceExecution"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportGenerator.2.1.8.0")]
        public string ReportGeneratorVersion {
            get {
                return ((string)(this["ReportGeneratorVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FVezzali")]
        public string LocalUser {
            get {
                return ((string)(this["LocalUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DeployDatabase {
            get {
                return ((string)(this["DeployDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string UpdateLocalUser {
            get {
                return ((string)(this["UpdateLocalUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string GetLatestAndCompile {
            get {
                return ((string)(this["GetLatestAndCompile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestCategory=UnitTest|TestCategory=IntegrationTest")]
        public string TestCategory {
            get {
                return ((string)(this["TestCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fernando.vezzali@fenergo.com")]
        public string SmtpTo {
            get {
                return ((string)(this["SmtpTo"]));
            }
        }
    }
}
